version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework:*"
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - "@angular/*"
  - package-ecosystem: npm
    directory: /scripts/screenshots
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
