spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://${LOCAL_MYSQL_DB_HOST}:${LOCAL_MYSQL_DB_PORT}/flowershop
    username: ${LOCAL_MYSQL_DB_USERNAME}
    password: ${LOCAL_MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update