-- Generated by scripts/tools/regenerate-product-seeds.mjs, do not edit.
-- Regenerate with: make seeds

create table if not exists product (
	id bigint not null auto_increment,
	category_name varchar(255) default null,
	description varchar(2000) default null,
	img_url varchar(2000) default null,
	name varchar(255) default null,
	price decimal(12,0) default null,
	type_name varchar(255) default null,
	primary key (id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table if not exists stock_level (
	id bigint not null auto_increment,
	branch_id bigint default null,
	product_id bigint default null,
	quantity int not null,
	primary key (id),
	unique key UKo3w3fq3nqjlhy6k7gq1ooemlb (branch_id, product_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;


insert into product (id, name, description, img_url, price, type_name, category_name) values (1, 'Wildflower In Flight Bouquet', 'With its feminine feel and European charm, this alluring glass cube is the perfect Mother''s Day surprise! It''s carefully hand-decorated and filled with a fresh bouquet of daisies and roses.', 'https://img.teleflora.com/images/o_0/l_flowers:T18M400C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T18M400C/Teleflora''sWildflowerInFlightBouquetPM', 1380000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (2, 'Art Glass Garden Bouquet', 'The shimmering, iridescent aqua blue glass of this stunning cylinder vase is the perfect partner for a fresh, fabulous bouquet of lavender roses, alstroemeria and tulips!', 'https://img.teleflora.com/images/o_0/l_flowers:T19E300C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T19E300C/Teleflora''sArtGlassGardenBouquetPM', 1610000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (3, 'Yours Truly Bouquet', 'A truly breathtaking tribute to your love, this romantic arrangement bursts with a dozen and a half red and white roses, nestled among delicate greens.', 'https://img.teleflora.com/images/o_0/l_flowers:TRS10-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TRS10-1C/YoursTrulyBouquetPM', 3565000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (4, 'Fabulous Flora Bouquet', 'Just fabulous! From its perky pink cube and perfect pink roses, to its textural greens and dramatic pink lilies, this chic bouquet is flora at its finest!', 'https://img.teleflora.com/images/o_0/l_flowers:TLR09-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TLR09-1C/Teleflora''sFabulousFloraBouquetPM', 1610000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (5, 'Endless Lovelies Bouquet', 'Timeless and touching, this serenely beautiful bouquet of peach and white blooms is perfectly presented in a classic mercury glass hurricane. Two gifts in one, it later transforms into a shimmering candleholder.', 'https://img.teleflora.com/images/o_0/l_flowers:TLR08-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TLR08-1C/Teleflora''sEndlessLoveliesBouquetPM', 1840000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (6, 'Punch Of Color Bouquet', 'A punch of sunset-inspired color, this bold, beautiful blend of hot pink roses and orange lilies in a classic glass vase will brighten any day!', 'https://img.teleflora.com/images/o_0/l_flowers:TEV56-2C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV56-2C/PunchOfColorBouquetPM', 2300000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (7, 'Pretty Paradise Bouquet', 'Send that special someone on a trip to paradise, no plane tickets required! This magical mix of luxurious pink, yellow and green blooms bursts with color, texture and personality. It''s a tropical treat they''ll never forget!', 'https://img.teleflora.com/images/o_0/l_flowers:TSD01-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TSD01-1C/PrettyParadiseBouquetPM', 5865000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (8, 'Joy Of Roses Bouquet', 'Pure joy! Two dozen wondrous white roses take center stage in this chic bouquet, delivered with stylish greens in a classic urn vase.', 'https://img.teleflora.com/images/o_0/l_flowers:TRS11-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TRS11-1C/JoyOfRosesBouquetPM', 2875000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (9, 'Intoxicating Beauty Bouquet', 'Luxuriate in the natural, intoxicating beauty of this chic arrangement. Inspired by a wild garden, this composition of whisper-peach roses, white lilies and moody purple hydrangea is beautifully presented in a modern ceramic planter.', 'https://img.teleflora.com/images/o_0/l_flowers:TEV56-8C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV56-8C/IntoxicatingBeautyBouquetPM', 6325000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (10, 'Forever Our Angel Bouquet by Teleflora', 'Elegant and emotional, this touching arrangement of rich red roses with delicate greens surrounds a peaceful porcelain angel sculpture keepsake.', 'https://img.teleflora.com/images/o_0/l_flowers:T280-2C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T280-2C/ForeverOurAngelBouquetbyTelefloraPM', 2990000, 'ROSES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (11, 'Vivid Love Bouquet', 'Bold and beautiful! This gorgeous jewel-toned arrangement is a stunning statement of devotion, wrapped with leaves for a stylish, modern touch.', 'https://img.teleflora.com/images/o_0/l_flowers:TEV55-4C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV55-4C/Teleflora''sVividLoveBouquetPM', 1380000, 'CARNATIONS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (12, 'Zen Artistry', 'Artistry, indeed. Looking more like modern sculpture than a floral arrangement, this striking bouquet surprises with delicate purple orchids, mini bamboo and a colorful mix of blooms - sure to improve any room''s feng shui.', 'https://img.teleflora.com/images/o_0/l_flowers:T81-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T81-1C/ZenArtistryPM', 1610000, 'CARNATIONS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (13, '''48 Ford Pickup Bouquet', 'Beep, beep! Say "Happy Birthday," "Happy Father''s Day," or "Keep on Truckin''!" to your favorite car buff with this whimsical bouquet, arranged in a reusable keepsake that will look great on his desk for years to come.', 'https://img.teleflora.com/images/o_0/l_flowers:T25-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T25-1C/Teleflora''s''48FordPickupBouquetPM', 1725000, 'CARNATIONS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (14, 'Your Special Day', 'Make a wish! Instead of a calorie-packed cake, send the birthday star a birthday cake of flowers. This unique arrangement features happy shades of pink, purple and white. And no birthday cake''s complete without candles!', 'https://img.teleflora.com/images/o_0/l_flowers:T16-3C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T16-3C/YourSpecialDayPM', 1955000, 'CARNATIONS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (15, 'Heart and Soul', 'Send someone this soulful floral gift and there''ll be no mistaking that you''re giving them your heart! A heart made entirely of red roses is nestled in a cloud of baby''s breath and ferns and presented in a tall red vase adorned with a pretty ribbon.', 'https://img.teleflora.com/images/o_0/l_flowers:T11Z102C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T11Z102C/HeartandSoulPM', 2300000, 'CARNATIONS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (16, 'Pretty And Posh Bouquet', 'Brighten any day with blushing blooms, cheerfully presented in a turquoise glass vase they''ll enjoy for years to come!', 'https://img.teleflora.com/images/o_0/l_flowers:TSP01-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TSP01-1C/Teleflora''sPrettyAndPoshBouquetPM', 1840000, 'LILIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (17, 'True Horizon Bouquet', 'As hopeful as the bright horizon ahead, this glorious white bouquet of hydrangea, roses, lilies and snapdragons is a peaceful tribute to a truly beloved.', 'https://img.teleflora.com/images/o_0/l_flowers:T281-4C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T281-4C/Teleflora''sTrueHorizonBouquetPM', 5175000, 'LILIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (18, 'Precious Petals Bouquet', 'A radiant celebration of faith, this bright bouquet of cheerful orange and pink blooms surrounds a reverent crystal cross keepsake. A precious addition to any special occasion.', 'https://img.teleflora.com/images/o_0/l_flowers:TEV57-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV57-1C/Teleflora''sPreciousPetalsBouquetPM', 2070000, 'LILIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (19, 'Dazzling Orchid', 'When you want to dazzle them, send this majestic purple orchid! Nestled in a bed of moss, the glorious living phalaenopsis plant looks lovely in this bubble-textured pink glass vase with glamorous metallic finish.', 'https://img.teleflora.com/images/o_0/l_flowers:T19S110A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T19S110A/Teleflora''sDazzlingOrchid', 1610000, 'ORCHIDS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (20, 'Divine Orchid', 'A duet of phalaenopsis orchids dance gracefully upward from a bed of natural seed gravel and moss. Presented in a serenely beautiful decorative planter, these tropical houseplants can thrive for years in the right conditions.', 'https://img.teleflora.com/images/o_0/l_flowers:T99-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T99-1A/DivineOrchid', 2300000, 'ORCHIDS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (21, 'Now and Zen', 'Unusual elements including pink ginger, green artichoke, river cane and green anthuriums make this Asian-inspired arrangement especially eye-catching. The tall, serene sculpture is presented in a dark wooden box for a very Zen effect.', 'https://img.teleflora.com/images/o_0/l_flowers:T82-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T82-1A/NowandZen', 3910000, 'ORCHIDS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (23, 'Sunny Day Pitcher of Cheer', 'Three cheers for sunny yellow! A happy pick for men and women, old and young, this sweet, summery arrangement of yellow and white flowers is delivered in our signature Sunny Day Pitcher!', 'https://img.teleflora.com/images/o_0/l_flowers:T57-1B,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T57-1B/Teleflora''sSunnyDayPitcherofCheerDX', 1955000, 'DAISIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (24, 'Sweet as a Daisy', 'Yellow daisies in a terra-cotta pot. Does it get any sweeter than that? Send sunshine someone''s way with this long-lasting gift of a yellow chrysanthemum plant.', 'https://img.teleflora.com/images/o_0/l_flowers:T95-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T95-1A/SweetasaDaisy', 690000, 'DAISIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (25, 'Lucky Ducky Bouquet', 'Wish the little lucky duck the warmest of welcomes with this classic keepsake! Bursting with yellow and blue blooms, this delightful ceramic duck container with a cute sailor''s cap.', 'https://img.teleflora.com/images/o_0/l_flowers:TNB09-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TNB09-1C/Teleflora''sLuckyDuckyBouquetPM', 1840000, 'DAISIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (26, 'Sunflower Beauty Bouquet', 'This magnificent arrangement of golden sunflowers and orange roses, presented in a hand-blown art glass vase, brings the beauty of an ocean sunset to any occasion.', 'https://img.teleflora.com/images/o_0/l_flowers:TEV57-5C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV57-5C/Teleflora''sSunflowerBeautyBouquetPM', 2645000, 'SUNFLOWERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (27, 'Pure Happiness', 'A sunny sunflower bouquet gets an autumnal spin with the addition of pretty bronze daisy mums and rich red roses. The cheerful autumn floral arrangement is rich with color, making it a stylish.', 'https://img.teleflora.com/images/o_0/l_flowers:T171-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T171-1C/PureHappinessPM', 2070000, 'SUNFLOWERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (28, 'Picnic in the Park', 'Send this colorful gift basket of flowers to your favorite garden lover or flower-loving grandmother. Like a miniature summer garden, the fresh cut flowers will brighten her kitchen counter, bedside table, coffee table.', 'https://img.teleflora.com/images/o_0/l_flowers:T152-3A_ENV,pg_6/w_1000,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T152-3A_ENV/PicnicinthePark', 2070000, 'SUNFLOWERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (29, 'Arrive In Style', 'Express your love with the eloquence of Shakespeare - without saying a word. She''ll adore this exquisite bouquet of roses and lilies and other pastel favorites in a classic ginger vase.', 'https://img.teleflora.com/images/o_0/l_flowers:T55-2C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T55-2C/ArriveInStylePM', 1380000, 'ALSTROEMERIA', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (30, 'Exotic Grace', 'Send good feng shui someone''s way with this striking arrangement. Orange flowers, gorgeous green ti leaves and small bamboo-like canes are arranged in a balanced, Zen-like composition.', 'https://img.teleflora.com/images/o_0/l_flowers:T77-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T77-1C/Teleflora''sExoticGracePM', 2070000, 'ALSTROEMERIA', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (31, 'Fall in Love', 'True romance! Express your love with this gorgeous flower arrangement, bursting with romantic flowers in passionate shades of red, purple and pink. Your beloved recipient is sure to fall in love with it - and you!', 'https://img.teleflora.com/images/o_0/l_flowers:T173-2C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T173-2C/Teleflora''sFallinLovePM', 1380000, 'ALSTROEMERIA', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (32, 'Make Her Day', 'This sweet bouquet includes a vast array of green miniature hydrangea and light pink spray roses arranged in our citrus green glass cube.', 'https://img.teleflora.com/images/o_0/l_flowers:TEV20-3C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV20-3C/MakeHerDaybyTelefloraPM', 1840000, 'ASTERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (33, 'Daisy Daydreams', 'Get a handle on spring with this delightful array of floral favorites in a charming white bamboo basket accented with lavender ribbon. Surprise someone who could use a lift. It will make you both happy.', 'https://img.teleflora.com/images/o_0/l_flowers:T11Z105C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T11Z105C/DaisyDaydreamsPM', 1380000, 'ASTERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (34, 'Heart''s Delight', 'A sweetly romantic birthday present or heartfelt gift for a friend, this delightful arrangement pampers her with soft lavenders, deep purples and pretty pinks - not to mention the modern glass cube vase she''ll use again and again!', 'https://img.teleflora.com/images/o_0/l_flowers:T16-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T16-1A/Heart''sDelightbyTeleflora', 1725000, 'ASTERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (35, 'Grand Gesture', 'A unique take on the traditional topiary, this modern arrangement of graceful calla lilies among tropical leaves is a grand gesture indeed. Presented in a natural bamboo dish, it''s both soft and strong.', 'https://img.teleflora.com/images/o_0/l_flowers:T78-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T78-1A/Teleflora''sGrandGesture', 2530000, 'CALLA LILIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (36, 'My Fair Lady', 'Who''s the fairest of them all? Elegant callas, without a doubt. The graceful white flowers are accented with Zen greenery in a tall glass vase for a modern, romantic arrangement.', 'https://img.teleflora.com/images/o_0/l_flowers:T83-1B,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T83-1B/MyFairLadybyTelefloraDX', 4025000, 'CALLA LILIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (37, 'Moondance', 'As magical as a moondance. Gracefully arching callas are balanced by lush white hydrangea and exotic orchids in this gorgeous green and white arrangement. It makes a chic statement in a tall glass vase.', 'https://img.teleflora.com/images/o_0/l_flowers:T79-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T79-1A/Moondance', 3795000, 'CALLA LILIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (38, 'Baby''s Wow Wagon', 'Hitch your wagon to a star! This little red wagon is a flower arrangement and nursery decoration all in one. A top-selling baby gift, it''s filled with bold blooms of red, yellow and white.', 'https://img.teleflora.com/images/o_0/l_flowers:T35-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T35-1C/Baby''sWowWagonbyTeleflora-BoyPM', 1725000, 'CHRYSANTHEMUMS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (39, 'Tropical Bliss', 'Escape to tropical bliss with this stunning, sculptural presentation. Sun-kissed lilies, tropical red ti leaves and eye-catching red ginger are mixed with other colorful flowers and leaves in a decorative bamboo planter.', 'https://img.teleflora.com/images/o_0/l_flowers:T85-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T85-1A/Teleflora''sTropicalBliss', 2530000, 'CHRYSANTHEMUMS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (40, 'Time Together Bouquet', 'Simply charming, this sweet lavender bouquet of asters and chrysanthemums is accented with our shimmering pink keepsake vase she''ll always treasure.', 'https://img.teleflora.com/images/o_0/l_flowers:TEV34-1B,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV34-1B/Teleflora''sTimeTogetherBouquetDX', 1380000, 'CHRYSANTHEMUMS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (41, 'Beachside Bliss', 'Throwing a summer soiree at the Hamptons? Planning a wedding on the sand? Or perhaps you just want to send an ocean breeze someone''s way. In any event, this tin pail of summer blooms is a beautiful, beachy choice.', 'https://img.teleflora.com/images/o_0/l_flowers:T162-1B,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T162-1B/BeachsideBlissDX', 2415000, 'DAHLIAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (42, 'Lush and Lovely', 'It''s elegant, chic, even stunning. But your guests will simply describe it as "Wow!" This luxuriously lush, incredibly stylish arrangement gathers orchids, roses, hydrangea, dahlias and cushion mums.', 'https://img.teleflora.com/images/o_0/l_flowers:T172-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T172-1A/Teleflora''sLushandLovely', 3680000, 'DAHLIAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (43, 'Summer Chic', 'Feeling hot, hot, hot! This sizzling summer floral arrangement mixes hot pink dahlias and carnations with bright orange roses and lilies in an orange cube vase. It''s the floral equivalent of a trip to Miami in July!', 'https://img.teleflora.com/images/o_0/l_flowers:T158-1B,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T158-1B/Teleflora''sSummerChicDX', 1725000, 'DAHLIAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (44, 'Seaside Centerpiece', 'Having a beach wedding or beach themed celebration? This beautiful centerpiece captures the wonder and romance of the seaside, making it a perfect choice for beach wedding flowers.', 'https://img.teleflora.com/images/o_0/l_flowers:T184-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T184-1A/Teleflora''sSeasideCenterpiece', 2300000, 'DELPHINIUMS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (45, 'Baby''s First Block', 'He''ll be building block towers soon enough! For now, celebrate him with this beautiful keepsake baby block. Filled with soft blues and whites, the glass block can be used later in baby''s room.', 'https://img.teleflora.com/images/o_0/l_flowers:T34-2C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T34-2C/Baby''sFirstBlockbyTeleflora-BluePM', 1725000, 'DELPHINIUMS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (46, 'Turn Up The Pink Bouquet', 'Pop goes the pink! A gorgeously chic gift for any occasion, this perky pink and orange bouquet is pure fun, especially when it''s hand-delivered in our fabulous fuchsia Cube!', 'https://img.teleflora.com/images/o_0/l_flowers:TEV33-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV33-1C/Teleflora''sTurnUpThePinkBouquetPM', 1840000, 'GERBERAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (47, 'Brilliant Birthday Blooms', 'There''s no mistaking this bouquet for anything but a Happy Birthday wish! With its colorful streamers and birthday candle design, this bright arrangement is perfect as a great party centerpiece.', 'https://img.teleflora.com/images/o_0/l_flowers:T28-1C,pg_6/w_368,h_460,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T28-1C/Teleflora''sBrilliantBirthdayBloomsPM', 1495000, 'GERBERAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (48, 'Rainbow Rays Potted Gerbera', 'In living color! Send them a lovely, long-lasting gift with this potted red gerbera daisy plant. An exceptional value, the happy houseplant is presented in a red-glazed terra-cotta pot that can be used to brighten up.', 'https://img.teleflora.com/images/o_0/l_flowers:T95-5A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T95-5A/RainbowRaysPottedGerbera-Red', 690000, 'GERBERAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (49, 'Ticket to Paradise', 'As lush and serene as a tropical sunset, this paradise of feminine blooms is a unique way to send your best wishes. The well-balanced arrangement is both chic and Zen, with its graceful callas.', 'https://img.teleflora.com/images/o_0/l_flowers:T81-3A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T81-3A/Teleflora''sTickettoParadise', 2760000, 'HYDRANGEAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (50, 'Happy Hydrangea', 'Have you ever seen a happier plant? The hydrangea''s beautiful, billowing blooms are beloved by all. Send this 6-inch potted blue hydrangea plant as a housewarming gift or simply to brighten someone''s day with a living gift.', 'https://img.teleflora.com/images/o_0/l_flowers:T89-2A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T89-2A/HappyHydrangea-Blue', 1610000, 'HYDRANGEAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (51, 'Everything''s Beachy', 'What''s more beachy than a bouquet that comes with a built-in beach? This delightful summer arrangement is delivered in an acrylic vase that has an invisible panel holding a beach scene of seashells.', 'https://img.teleflora.com/images/o_0/l_flowers:T163-3A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T163-3A/Everything''sBeachybyTeleflora', 2185000, 'HYDRANGEAS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (52, 'Spring Favorites', 'Roses and tulips and hyacinth - oh, my! All your spring favorites are here, whimsically arranged in a shallow terra-cotta pot in pretty pastel spring colors. The fun potted flower arrangement is a wonderful way to welcome a new baby.', 'https://img.teleflora.com/images/o_0/l_flowers:T149-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T149-1C/SpringFavoritesPM', 2070000, 'IRISES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (53, 'Fairest of All', 'A fairy tale…in flowers! Delicate ivy climbs the handle of this round wicker basket that''s home to a feminine garden of fuchsia flowers. You can almost imagine garden sprites dancing through the country style arrangement!', 'https://img.teleflora.com/images/o_0/l_flowers:T147-3B,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T147-3B/FairestofAllDX', 1955000, 'LISIANTHUS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (54, 'Napa Valley Centerpiece', 'Invite the natural beauty and wonder of Napa Valley to your wedding! This beautiful white flower centerpiece delivers innocence and elegance along with a stunning array of white blossoms and graceful greens.', 'https://img.teleflora.com/images/o_0/l_flowers:T198-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T198-1A/Teleflora''sNapaValleyCenterpiece', 3220000, 'LISIANTHUS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (55, 'Breathless Bouquet', 'Go all-out for style with this stunning silver vase filled with lavender roses and other lush blooms, and crowned by a snow-white orchid. She''ll appreciate your impeccable taste and love the way you show your love for her.', 'https://img.teleflora.com/images/o_0/l_flowers:T403-2B,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T403-2B/Teleflora''sBreathlessBouquetDX', 2415000, 'LISIANTHUS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (56, 'Pretty in Peony', 'Good and girly! A fabulous pick for a stylish sister, friend or girlfriend, this trendy peony bouquet pairs lush, cloud-white hydrangea with the luscious beauty of pink peonies.', 'https://img.teleflora.com/images/o_0/l_flowers:T145-2C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T145-2C/Teleflora''sPrettyinPeonyPM', 2070000, 'PEONIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (57, 'Perfect Peonies', 'Peony perfection! Everyone loves the lush, cloud-like appearance of fresh cut peonies. The romantic, feminine bloom is a popular summer wedding flower.', 'https://img.teleflora.com/images/o_0/l_flowers:T144-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T144-1C/Teleflora''sPerfectPeoniesPM', 3105000, 'PEONIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (58, 'Serene Spring Peony Bouquet', 'Chic and serene, this dreamy bouquet of wondrous white peonies and creamy blooms in a milk jug vase sends your very best wishes for a stylish spring!', 'https://img.teleflora.com/images/o_0/l_flowers:TSP06-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TSP06-1C/SereneSpringPeonyBouquetPM', 2760000, 'PEONIES', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (59, 'Love Everlasting Bouquet', 'Celebrate the beauty of a life fully lived with this lovely array of pink lilies, blue hydrangea and other floral favorites in a sparkling Ming urn.', 'https://img.teleflora.com/images/o_0/l_flowers:T267-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T267-1C/LoveEverlastingBouquetPM', 2990000, 'STOCK', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (60, 'Enchanted Cottage', 'As enchanting as coming across a hidden cottage in the countryside! Lush white roses and purple stock mix with delicate lavender waxflower and green pitta negra for an elegant English garden look.', 'https://img.teleflora.com/images/o_0/l_flowers:T50-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T50-1C/Teleflora''sEnchantedCottagePM', 1610000, 'STOCK', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (61, 'Joyful Memory', 'Lavender and white sympathy flowers make a grand statement in this joyful bouquet. Cherish your memories with this lasting remembrance of lavender larkspur and roses, deep purple asters.', 'https://img.teleflora.com/images/o_0/l_flowers:T251-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T251-1C/JoyfulMemoryPM', 3105000, 'STOCK', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (62, 'Love''s Tapestry', 'This stylish, uplifting mix of sympathy flowers for the service is bursting with color. The tall arrangement features an array of flowers that will touch everyone''s hearts, artistically arranged in a sympathy basket.', 'https://img.teleflora.com/images/o_0/l_flowers:T218-2A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T218-2A/Love''sTapestry', 2415000, 'SNAPDRAGONS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (63, 'Vivid Recollections', 'Send sunshine to show you care. A symbol of friendship, these yellow sympathy flowers are accented with pretty pink carnations for a classic sympathy basket that will warm anyone''s heart.', 'https://img.teleflora.com/images/o_0/l_flowers:T218-4A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T218-4A/VividRecollections', 1725000, 'SNAPDRAGONS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (64, 'Passionate Purple Tulips', 'Tulips this tantalizing need no decoration! Celebrate a spring birthday, send your love, or simply let someone know you''re thinking of them with this stunning monochrome bouquet.', 'https://img.teleflora.com/images/o_0/l_flowers:T148-2C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T148-2C/PassionatePurpleTulipsPM', 2415000, 'TULIPS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (65, 'Sweet Surrender Bouquet', 'Surrender to the elegant, natural beauty of tulips. Twenty five red and pink flowers are presented in our graceful Silver Reflections vase. It''s a premium presentation that highlights the tulips'' natural beauty.', 'https://img.teleflora.com/images/o_0/l_flowers:T402-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T402-1C/Teleflora''sSweetSurrenderBouquetPM', 2138000, 'TULIPS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (66, 'Sunny Yellow Tulips', 'Sunny yellow tulips are a sure sign of spring. Even if the weather is not cooperating, you can be sure the person who receives this bright bouquet will feel the warmth of your message.', 'https://img.teleflora.com/images/o_0/l_flowers:T140-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T140-1C/SunnyYellowTulipsPM', 2415000, 'TULIPS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (67, 'Exquisite Elegance Bouquet', 'A sculpture of blooms. Elevate any occasion with this exquisite masterpiece of elegant orchids, roses and graphic succulents, dripping with amaranthus and arranged in an oversized glass jug.', 'https://img.teleflora.com/images/o_0/l_flowers:TEV56-9C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV56-9C/ExquisiteEleganceBouquetPM', 4025000, 'TROPICAL FLOWERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (68, 'Regally Yours Orchid', 'Regally beautiful, this amazing orange cymbidium orhid plant in a gorgeous pot is a lovely, living gift that will make them smile every day! A stunning surprise for any occasion.', 'https://img.teleflora.com/images/o_0/l_flowers:TPL04-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TPL04-1A/Teleflora''sRegallyYoursOrchid', 2530000, 'TROPICAL FLOWERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (69, 'Fantasy Found', 'Minimalist beauty abounds in this unique mix of orchids, gladioli and leucadendron. Delivered in a large bamboo cube, it''s sure to impress men and women alike.', 'https://img.teleflora.com/images/o_0/l_flowers:T84-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T84-1A/Teleflora''sFantasyFound', 2415000, 'TROPICAL FLOWERS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (70, 'Summer Daydream Bouquet', 'A daydream come true, this bold bouquet is an instant dose of sunshine! Celebrate your special someone with sunny blooms arranged in our rich blue vase.', 'https://img.teleflora.com/images/o_0/l_flowers:TEV31-4C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/TEV31-4C/Teleflora''sSummerDaydreamBouquetPM', 1495000, 'MIXED BOUQUETS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (71, 'Blossoms in Vogue', 'High-fashion flowers for the style-minded! This modern presentation of multicolored roses and green hydrangea has a tropical feel thanks to the hot color palette and the aspidistra leaves in the vase.', 'https://img.teleflora.com/images/o_0/l_flowers:T74-1C,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T74-1C/BlossomsinVoguePM', 2185000, 'MIXED BOUQUETS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (72, 'Island Dreams', 'Exotic meets chic. Presented in a black glass cube, this artistic gift features bright, tropical blooms framed by folded red ti leaves. It''s an energizing choice for a man or woman.', 'https://img.teleflora.com/images/o_0/l_flowers:T85-2A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T85-2A/Teleflora''sIslandDreams', 2300000, 'MIXED BOUQUETS', 'FLOWERS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (73, 'Secret Garden Basket', 'Imagine walking into a secret fern grotto. This lush garden arrangement features the delicate fronds of maidenhair and Boston ferns mixed with colorful kalanchoe and pink hypoestes.', 'https://img.teleflora.com/images/o_0/l_flowers:T96-2A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T96-2A/SecretGardenBasket', 1610000, 'BLOOMING PLANTS', 'PLANTS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (74, 'Health Nut Basket', 'Healthy fruits and nuts are presented with a pretty potted kalanchoe plant in a large wicker basket. Health food has never looked so good!', 'https://img.teleflora.com/images/o_0/l_flowers:T108-2A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T108-2A/HealthNutBasket', 1725000, 'BLOOMING PLANTS', 'PLANTS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (75, 'Stylish Plant Assortment', 'A modern way to send mixed plants! This colorful, long-lasting gift is presented in a dark vase with clean lines, making it a perfect pick for the home or office. Also an excellent get-well gift!', 'https://img.teleflora.com/images/o_0/l_flowers:T106-3A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T106-3A/StylishPlantAssortment', 1840000, 'BLOOMING PLANTS', 'PLANTS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (76, 'Stately Croton', 'Not your typical houseplant! With its bright tropical foliage, exotic appearance and Asian-inspired square planter, this potted croton plant is an eye-catching natural addition to any room.', 'https://img.teleflora.com/images/o_0/l_flowers:T106-2A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T106-2A/StatelyCroton', 1725000, 'GREEN PLANTS', 'PLANTS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (77, 'Money Tree', 'Harmonize the five elements within a space, bring good fortune and prosperity, and improve the flow of "chi" with a money tree! The money tree - or Pachira - is thought to bring good luck.', 'https://img.teleflora.com/images/o_0/l_flowers:T12Z101A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T12Z101A/MoneyTree', 1150000, 'GREEN PLANTS', 'PLANTS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (78, 'Peaceful Zen Garden', 'The gift of Zen. Send peace someone''s way with this elegant, eye-pleasing arrangement of low-maintenance succulent plants. Presented in a brown bamboo container, the plants are accented with smooth river rocks.', 'https://img.teleflora.com/images/o_0/l_flowers:T101-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T101-1A/Teleflora''sPeacefulZenGarden', 1380000, 'GREEN PLANTS', 'PLANTS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (79, 'Regal Orchids', 'A trio of colorful orchids is an elegant way to wish someone well. Presented in a beautiful white ceramic planter are three miniature phalaenopsis orchid plants.', 'https://img.teleflora.com/images/o_0/l_flowers:T103-1A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T103-1A/RegalOrchids', 4025000, 'ORCHIDS & TROPICALS', 'PLANTS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into product (id, name, description, img_url, price, type_name, category_name) values (80, 'Opulent Orchids', 'Send Zen. A graceful white phaleanopsis orchid plant potted in a modern bamboo container is an enchanting gift for any occasion.', 'https://img.teleflora.com/images/o_0/l_flowers:T98-2A,pg_6/w_800,h_1000,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T98-2A/Teleflora''sOpulentOrchids', 2875000, 'ORCHIDS & TROPICALS', 'PLANTS') as v
on duplicate key update name = v.name, description = v.description, img_url = v.img_url, price = v.price, type_name = v.type_name, category_name = v.category_name;

insert into stock_level (branch_id, product_id, quantity) values
	(1, 1, 25),
	(1, 2, 25),
	(1, 3, 25),
	(1, 4, 25),
	(1, 5, 25),
	(1, 6, 25),
	(1, 7, 25),
	(1, 8, 25),
	(1, 9, 25),
	(1, 10, 25),
	(1, 11, 25),
	(1, 12, 25),
	(1, 13, 25),
	(1, 14, 25),
	(1, 15, 25),
	(1, 16, 25),
	(1, 17, 25),
	(1, 18, 25),
	(1, 19, 25),
	(1, 20, 25),
	(1, 21, 25),
	(1, 23, 25),
	(1, 24, 25),
	(1, 25, 25),
	(1, 26, 25),
	(1, 27, 25),
	(1, 28, 25),
	(1, 29, 25),
	(1, 30, 25),
	(1, 31, 25),
	(1, 32, 25),
	(1, 33, 25),
	(1, 34, 25),
	(1, 35, 25),
	(1, 36, 25),
	(1, 37, 25),
	(1, 38, 25),
	(1, 39, 25),
	(1, 40, 25),
	(1, 41, 25),
	(1, 42, 25),
	(1, 43, 25),
	(1, 44, 25),
	(1, 45, 25),
	(1, 46, 25),
	(1, 47, 25),
	(1, 48, 25),
	(1, 49, 25),
	(1, 50, 25),
	(1, 51, 25),
	(1, 52, 25),
	(1, 53, 25),
	(1, 54, 25),
	(1, 55, 25),
	(1, 56, 25),
	(1, 57, 25),
	(1, 58, 25),
	(1, 59, 25),
	(1, 60, 25),
	(1, 61, 25),
	(1, 62, 25),
	(1, 63, 25),
	(1, 64, 25),
	(1, 65, 25),
	(1, 66, 25),
	(1, 67, 25),
	(1, 68, 25),
	(1, 69, 25),
	(1, 70, 25),
	(1, 71, 25),
	(1, 72, 25),
	(1, 73, 25),
	(1, 74, 25),
	(1, 75, 25),
	(1, 76, 25),
	(1, 77, 25),
	(1, 78, 25),
	(1, 79, 25),
	(1, 80, 25) as v
on duplicate key update quantity = v.quantity;

insert into stock_level (branch_id, product_id, quantity) values
	(2, 1, 25),
	(2, 2, 25),
	(2, 3, 25),
	(2, 4, 25),
	(2, 5, 25),
	(2, 6, 25),
	(2, 7, 25),
	(2, 8, 25),
	(2, 9, 25),
	(2, 10, 25),
	(2, 11, 25),
	(2, 12, 25),
	(2, 13, 25),
	(2, 14, 25),
	(2, 15, 25),
	(2, 16, 25),
	(2, 17, 25),
	(2, 18, 25),
	(2, 19, 25),
	(2, 20, 25),
	(2, 21, 25),
	(2, 23, 25),
	(2, 24, 25),
	(2, 25, 25),
	(2, 26, 25),
	(2, 27, 25),
	(2, 28, 25),
	(2, 29, 25),
	(2, 30, 25),
	(2, 31, 25),
	(2, 32, 25),
	(2, 33, 25),
	(2, 34, 25),
	(2, 35, 25),
	(2, 36, 25),
	(2, 37, 25),
	(2, 38, 25),
	(2, 39, 25),
	(2, 40, 25),
	(2, 41, 25),
	(2, 42, 25),
	(2, 43, 25),
	(2, 44, 25),
	(2, 45, 25),
	(2, 46, 25),
	(2, 47, 25),
	(2, 48, 25),
	(2, 49, 25),
	(2, 50, 25),
	(2, 51, 25),
	(2, 52, 25),
	(2, 53, 25),
	(2, 54, 25),
	(2, 55, 25),
	(2, 56, 25),
	(2, 57, 25),
	(2, 58, 25),
	(2, 59, 25),
	(2, 60, 25),
	(2, 61, 25),
	(2, 62, 25),
	(2, 63, 25),
	(2, 64, 25),
	(2, 65, 25),
	(2, 66, 25),
	(2, 67, 25),
	(2, 68, 25),
	(2, 69, 25),
	(2, 70, 25),
	(2, 71, 25),
	(2, 72, 25),
	(2, 73, 25),
	(2, 74, 25),
	(2, 75, 25),
	(2, 76, 25),
	(2, 77, 25),
	(2, 78, 25),
	(2, 79, 25),
	(2, 80, 25) as v
on duplicate key update quantity = v.quantity;

insert into stock_level (branch_id, product_id, quantity) values
	(3, 1, 25),
	(3, 2, 25),
	(3, 3, 25),
	(3, 4, 25),
	(3, 5, 25),
	(3, 6, 25),
	(3, 7, 25),
	(3, 8, 25),
	(3, 9, 25),
	(3, 10, 25),
	(3, 11, 25),
	(3, 12, 25),
	(3, 13, 25),
	(3, 14, 25),
	(3, 15, 25),
	(3, 16, 25),
	(3, 17, 25),
	(3, 18, 25),
	(3, 19, 25),
	(3, 20, 25),
	(3, 21, 25),
	(3, 23, 25),
	(3, 24, 25),
	(3, 25, 25),
	(3, 26, 25),
	(3, 27, 25),
	(3, 28, 25),
	(3, 29, 25),
	(3, 30, 25),
	(3, 31, 25),
	(3, 32, 25),
	(3, 33, 25),
	(3, 34, 25),
	(3, 35, 25),
	(3, 36, 25),
	(3, 37, 25),
	(3, 38, 25),
	(3, 39, 25),
	(3, 40, 25),
	(3, 41, 25),
	(3, 42, 25),
	(3, 43, 25),
	(3, 44, 25),
	(3, 45, 25),
	(3, 46, 25),
	(3, 47, 25),
	(3, 48, 25),
	(3, 49, 25),
	(3, 50, 25),
	(3, 51, 25),
	(3, 52, 25),
	(3, 53, 25),
	(3, 54, 25),
	(3, 55, 25),
	(3, 56, 25),
	(3, 57, 25),
	(3, 58, 25),
	(3, 59, 25),
	(3, 60, 25),
	(3, 61, 25),
	(3, 62, 25),
	(3, 63, 25),
	(3, 64, 25),
	(3, 65, 25),
	(3, 66, 25),
	(3, 67, 25),
	(3, 68, 25),
	(3, 69, 25),
	(3, 70, 25),
	(3, 71, 25),
	(3, 72, 25),
	(3, 73, 25),
	(3, 74, 25),
	(3, 75, 25),
	(3, 76, 25),
	(3, 77, 25),
	(3, 78, 25),
	(3, 79, 25),
	(3, 80, 25) as v
on duplicate key update quantity = v.quantity;

insert into stock_level (branch_id, product_id, quantity) values
	(4, 1, 25),
	(4, 2, 25),
	(4, 3, 25),
	(4, 4, 25),
	(4, 5, 25),
	(4, 6, 25),
	(4, 7, 25),
	(4, 8, 25),
	(4, 9, 25),
	(4, 10, 25),
	(4, 11, 25),
	(4, 12, 25),
	(4, 13, 25),
	(4, 14, 25),
	(4, 15, 25),
	(4, 16, 25),
	(4, 17, 25),
	(4, 18, 25),
	(4, 19, 25),
	(4, 20, 25),
	(4, 21, 25),
	(4, 23, 25),
	(4, 24, 25),
	(4, 25, 25),
	(4, 26, 25),
	(4, 27, 25),
	(4, 28, 25),
	(4, 29, 25),
	(4, 30, 25),
	(4, 31, 25),
	(4, 32, 25),
	(4, 33, 25),
	(4, 34, 25),
	(4, 35, 25),
	(4, 36, 25),
	(4, 37, 25),
	(4, 38, 25),
	(4, 39, 25),
	(4, 40, 25),
	(4, 41, 25),
	(4, 42, 25),
	(4, 43, 25),
	(4, 44, 25),
	(4, 45, 25),
	(4, 46, 25),
	(4, 47, 25),
	(4, 48, 25),
	(4, 49, 25),
	(4, 50, 25),
	(4, 51, 25),
	(4, 52, 25),
	(4, 53, 25),
	(4, 54, 25),
	(4, 55, 25),
	(4, 56, 25),
	(4, 57, 25),
	(4, 58, 25),
	(4, 59, 25),
	(4, 60, 25),
	(4, 61, 25),
	(4, 62, 25),
	(4, 63, 25),
	(4, 64, 25),
	(4, 65, 25),
	(4, 66, 25),
	(4, 67, 25),
	(4, 68, 25),
	(4, 69, 25),
	(4, 70, 25),
	(4, 71, 25),
	(4, 72, 25),
	(4, 73, 25),
	(4, 74, 25),
	(4, 75, 25),
	(4, 76, 25),
	(4, 77, 25),
	(4, 78, 25),
	(4, 79, 25),
	(4, 80, 25) as v
on duplicate key update quantity = v.quantity;

insert into stock_level (branch_id, product_id, quantity) values
	(5, 1, 25),
	(5, 2, 25),
	(5, 3, 25),
	(5, 4, 25),
	(5, 5, 25),
	(5, 6, 25),
	(5, 7, 25),
	(5, 8, 25),
	(5, 9, 25),
	(5, 10, 25),
	(5, 11, 25),
	(5, 12, 25),
	(5, 13, 25),
	(5, 14, 25),
	(5, 15, 25),
	(5, 16, 25),
	(5, 17, 25),
	(5, 18, 25),
	(5, 19, 25),
	(5, 20, 25),
	(5, 21, 25),
	(5, 23, 25),
	(5, 24, 25),
	(5, 25, 25),
	(5, 26, 25),
	(5, 27, 25),
	(5, 28, 25),
	(5, 29, 25),
	(5, 30, 25),
	(5, 31, 25),
	(5, 32, 25),
	(5, 33, 25),
	(5, 34, 25),
	(5, 35, 25),
	(5, 36, 25),
	(5, 37, 25),
	(5, 38, 25),
	(5, 39, 25),
	(5, 40, 25),
	(5, 41, 25),
	(5, 42, 25),
	(5, 43, 25),
	(5, 44, 25),
	(5, 45, 25),
	(5, 46, 25),
	(5, 47, 25),
	(5, 48, 25),
	(5, 49, 25),
	(5, 50, 25),
	(5, 51, 25),
	(5, 52, 25),
	(5, 53, 25),
	(5, 54, 25),
	(5, 55, 25),
	(5, 56, 25),
	(5, 57, 25),
	(5, 58, 25),
	(5, 59, 25),
	(5, 60, 25),
	(5, 61, 25),
	(5, 62, 25),
	(5, 63, 25),
	(5, 64, 25),
	(5, 65, 25),
	(5, 66, 25),
	(5, 67, 25),
	(5, 68, 25),
	(5, 69, 25),
	(5, 70, 25),
	(5, 71, 25),
	(5, 72, 25),
	(5, 73, 25),
	(5, 74, 25),
	(5, 75, 25),
	(5, 76, 25),
	(5, 77, 25),
	(5, 78, 25),
	(5, 79, 25),
	(5, 80, 25) as v
on duplicate key update quantity = v.quantity;

insert into stock_level (branch_id, product_id, quantity) values
	(6, 1, 25),
	(6, 2, 25),
	(6, 3, 25),
	(6, 4, 25),
	(6, 5, 25),
	(6, 6, 25),
	(6, 7, 25),
	(6, 8, 25),
	(6, 9, 25),
	(6, 10, 25),
	(6, 11, 25),
	(6, 12, 25),
	(6, 13, 25),
	(6, 14, 25),
	(6, 15, 25),
	(6, 16, 25),
	(6, 17, 25),
	(6, 18, 25),
	(6, 19, 25),
	(6, 20, 25),
	(6, 21, 25),
	(6, 23, 25),
	(6, 24, 25),
	(6, 25, 25),
	(6, 26, 25),
	(6, 27, 25),
	(6, 28, 25),
	(6, 29, 25),
	(6, 30, 25),
	(6, 31, 25),
	(6, 32, 25),
	(6, 33, 25),
	(6, 34, 25),
	(6, 35, 25),
	(6, 36, 25),
	(6, 37, 25),
	(6, 38, 25),
	(6, 39, 25),
	(6, 40, 25),
	(6, 41, 25),
	(6, 42, 25),
	(6, 43, 25),
	(6, 44, 25),
	(6, 45, 25),
	(6, 46, 25),
	(6, 47, 25),
	(6, 48, 25),
	(6, 49, 25),
	(6, 50, 25),
	(6, 51, 25),
	(6, 52, 25),
	(6, 53, 25),
	(6, 54, 25),
	(6, 55, 25),
	(6, 56, 25),
	(6, 57, 25),
	(6, 58, 25),
	(6, 59, 25),
	(6, 60, 25),
	(6, 61, 25),
	(6, 62, 25),
	(6, 63, 25),
	(6, 64, 25),
	(6, 65, 25),
	(6, 66, 25),
	(6, 67, 25),
	(6, 68, 25),
	(6, 69, 25),
	(6, 70, 25),
	(6, 71, 25),
	(6, 72, 25),
	(6, 73, 25),
	(6, 74, 25),
	(6, 75, 25),
	(6, 76, 25),
	(6, 77, 25),
	(6, 78, 25),
	(6, 79, 25),
	(6, 80, 25) as v
on duplicate key update quantity = v.quantity;
